### ISSUE TITLE
Large packs seem to kill the html page

### ISSUE THREAD

**Issue by mezz** [mezz/TextureDump#2]
I ran TextureDump on the HermitPack, and the html page is not responsive to hovering except the first (ridiculously giant) 512x512 texture.

**Comment by AtomicBlom** [comment]
I've seen this on ForgeCraft, it seemed to be caused by a botania texture that was 60x60 that broke the grid I made for fast lookups.

**Comment by AtomicBlom** [comment]
This should be fixed by https://github.com/mezz/TextureDump/commit/41c17b68d8aa26fb3e6bef814c43753cd6d46827

**Comment by mezz** [comment]
Confirmed, works great!

**Comment by mezz** [comment]
I found some even larger packs with even more ridiculous textures and it got slow.

**Comment by Drullkus** [comment]
You talking about armor stands and that ridiculous big M texture? ಠ_ಠ

**Comment by AtomicBlom** [comment]
I'm not 100% sure, but I think I got this to load faster by preallocating the arrays. I don't think I'm going to be able to get it any faster unless I pre-process the data Java side.

I can't seem to find a way to get JavaScript to do parallel processing while writing back to shared memory.

Failing that, I might need to find a way to background the processing and stick a loading bar on it.

**Comment by mezz** [comment]
The slowness seems to be with highlighting things, not the page loading. I can hover... wait... wait... and  then it shows it as hovered.

**Comment by AtomicBlom** [comment]
Sorry, I missed that it was the highlighting that was the issue, I just pushed a couple of changes that reduce the amount of processing that needs to be done.

Another thing to perhaps test would be changing these values:
https://github.com/mezz/TextureDump/blob/master/src/main/resources/assets/texturedump/page.html#L18

setting it to say, 64 or 32 increases the number of cells in the grid and reduces the number of sprites that could be occupying that cell (so, less to iterate over at the expense of more memory)

**Comment by mezz** [comment]
With your changes it's working  better than before but still gets stuck some places. I'll play around with that value and see what happens.

**Comment by AtomicBlom** [comment]
Which modpack? I'll give it a spin after the kids are in bed

**Comment by mezz** [comment]
https://mods.curse.com/modpacks/minecraft/252375-explorational-fun

**Comment by mezz** [comment]
The issue seems to occur when highlighting a texture that is smaller than the ones it's next to. When I set the cellsize to 32x32 it works much better but still has occasional pauses.

**Comment by mezz** [comment]
This is fixed now.
